# - name: Copy binary to path
#   become: yes
#   ansible.builtin.copy:
#     src: "{{ item }}"
#     dest: "/usr/bin/{{ item }}"
#     mode: 0755
#   loop:
#     - openwec
#     - openwecd
#   notify: service-restart

- name: Copy systemd unit file
  become: yes
  ansible.builtin.template:
    src: openwec.service.j2
    dest: /etc/systemd/system/openwec.service
    mode: 0644
  notify:
    - daemon-reload
    - service-restart

- name: Copy openwec config
  become: yes
  ansible.builtin.template:
    src: openwec.conf.toml.j2
    dest: /etc/openwec.conf.toml
    mode: 0400
    owner: "{{ wec_user }}"
    group: "{{ wec_group }}"
  notify: service-restart

- name: Copy openwec keytab
  become: yes
  ansible.builtin.copy:
    src: wec.keytab
    dest: /etc/wec.keytab
    mode: 0400
    owner: "{{ wec_user }}"
    group: "{{ wec_group }}"
  notify: service-restart

- name: Create db path
  ansible.builtin.file:
    state: directory
    path: /var/openwec/
    mode: 0755
    owner: "{{ wec_user }}"
    group: "{{ wec_group }}"

- name: Create log path
  ansible.builtin.file:
    state: directory
    path: /var/log/wec.log/
    mode: 0755
    owner: "{{ wec_user }}"
    group: "{{ wec_group }}"
